branch-defaults:
  default:
    environment: symkala-dev5
global:
  application_name: symkala
  default_ec2_keyname: symkala
  default_platform: 64bit Amazon Linux 2015.09 v2.0.4 running Python 2.7
  default_region: us-east-1
  profile: eb-cli
  sc: null
