# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-06 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symkalaweb', '0012_auto_20160509_1346'),
        ('symkalaweb', '0002_auto_20160602_1534'),
    ]

    operations = [
    ]
