# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-23 21:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('symkalaweb', '0013_auto_20160523_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 21, 51, 30, 152000, tzinfo=utc)),
        ),
    ]
