# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 16:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('symkalaweb', '0014_auto_20160523_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 24, 16, 2, 36, 939000, tzinfo=utc)),
        ),
    ]
